//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int cid { get; set; }
        public string cname { get; set; }
        public string cpassword { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string mail { get; set; }
        public string caddress { get; set; }
        public string phone { get; set; }
        public string aadhar { get; set; }
    }
}
