//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dll
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int roomno { get; set; }
        public string roomtype { get; set; }
        public Nullable<bool> roomavailability { get; set; }
        public Nullable<bool> ac { get; set; }
    
        public virtual type type { get; set; }
    }
}
